[features]
seeds = false
[programs.localnet]
solana_twitter = "AdGdR4tVHcxa36vEvPGh9QHsAMLAD8861puJzr6mntJj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rusiru/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
rusiru = "echo 'Hello Rusiru!'"
